dynamodb_name = "awsfirst"
ecr_name = "awsfirst"
lambda_name = "awsfirst"
api_name = "awsfirst"
ecs_cluster_name = "awsfirst-cluster"
ecs_task_def_name = "awsfirst-task"
ecs_service_name = "awsfirst-service"
ecs_execution_role = "arn:aws:iam::941603547826:role/ecsTaskExecutionRole"